server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Reloj-service
          uri: lb://Reloj-service
          predicates:
            - Path=/Reloj/**
        - id: CalculoPlanilla-service
          uri: lb://CalculoPlanilla-service
          predicates:
            - Path=/CalculoPlanilla/**
        - id: HoraExtra-service
          uri: lb://HoraExtra-service
          predicates:
            - Path=/HoraExtra/**
        - id: Justificativos-service
          uri: lb://Justificativos-service
          predicates:
            - Path=/Justificativos/**
        - id: ReportePlanilla-service
          uri: lb://ReportePlanilla-service
          predicates:
            - Path=/ReportePlanilla/**